### ISSUE TITLE
Error out if proxynova is down or has no proxies available

### ISSUE THREAD

**Issue by darthbear** [darthbear/scrapy-proxynova#2]

**Comment by svetlyak40wt** [comment]
Hot to reproduce.

**Comment by darthbear** [comment]
Yeah, errors are different every time. Sometime the server is clearly down, sometimes it times out, sometimes the db is down so the page loads but without any proxy. The latter happened to me this morning and the spider started with an empty list of proxies resulting in a lot of errors before I realized what happened.

One thing we can do maybe is if we cannot connect to the site (timeout or error 500) or list of proxies is empty then throw an error?

**Comment by svetlyak40wt** [comment]
Well, this is a good solution.
