### ISSUE TITLE
Have a lock mechanism to prevent multiple scrapy instances to generate proxy lists at the same time

### ISSUE THREAD

**Issue by darthbear** [darthbear/scrapy-proxynova#3]
If scrapy is run multiple times in separate processes, we want to prevent them to all do the same job and try to generate a proxy list. Rather the first one should generate the list and the other ones wait for it to complete before starting crawling.

**Comment by svetlyak40wt** [comment]
It is easier to move proxy collection code into a separate command line tool and call it manually as needed. And in the middleware just check if file exists and not empty.

By the way. Why do you use JSON for file format? Why not a one proxy's IP:PORT per line in plain text?

**Comment by darthbear** [comment]
Agree, I guess that's easier. Yeah no real reason why I use JSON, one proxy per line in plain text would make more sense.

**Comment by darthbear** [comment]
wrote proxies in plain text, one server per line
proxies have to be generated by running proxies.py
