### ISSUE TITLE
Got an error

### ISSUE THREAD

**Issue by yasoob** [darthbear/scrapy-proxynova#8]
I got this error while running the example project 
`Error: Cannot find any available proxies`
I tried accessing the proxy page from my browser but proxy nova  said that this list is currently offline so i think it's proxynova issue rather than scrapy-proxynova.

**Comment by svetlyak40wt** [comment]
I know it. They closed their API few months ago. Probably, it is better to rollback a previous version which parsed HTML page from proxynova.
